import React, { useState, useEffect } from 'react';
import {Button, Form, Col, Container, Row} from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import ExamDetails from '../ExamDetails/ExamDetails.js'
import './form.css'

function XrayForm() {
    const initialValues = {
        PATIENT_ID: "",
        AGE: "",
        SEX: "",
        ZIP: "",
        LATEST_BMI: "",
        LATESTWEIGHT: "",
        ICU_Admit: "",
        NUM_ICU_admits: "",
        MORTALITY: "",
        png_filename: "",
        isSubmitted: false,
    };


    const navigate = useNavigate()

    const [allValues, setAllValues] = useState(initialValues)

    const handleOnchange = (e) => {
        
        setAllValues({...allValues, [e.target.name] : e.target.value});
    }

    const handleOnClick = (e) => {
        e.preventDefault();
        setAllValues({...allValues, isSubmitted: true})
        // navigate('/x-ray')
    }

    useEffect(() => {
        localStorage.setItem('allValues', JSON.stringify(allValues));
      }, [allValues]);

        return (
            <div className="centerform">
                {allValues.isSubmitted ? 
                    <ExamDetails xray={allValues}/> :
                    <Form>
                        <Form.Group controlId="formPatientId">
                            <Form.Label>Patient ID</Form.Label>
                            <Form.Control 
                            value={allValues.PATIENT_ID}
                            name="patientId" 
                            type="text" 
                            placeholder="Enter Patient ID"
                            onChange={handleOnchange} />
                        </Form.Group> 

                        {/* EXAM_ID MIGHT NEED TO BE GENERATED BY BD? */}
                        {/* <Form.Group controlId="formExamId">
                            <Form.Label>Exam ID</Form.Label>
                            <Form.Control 
                            value={allValues.examId}
                            name="examId" 
                            type="text" 
                            placeholder="Enter Exam ID"
                            onChange={handleOnchange} />
                        </Form.Group> */}
                        <Form.Group controlId="formAge">
                            <Form.Label>Age</Form.Label>
                            <Form.Control 
                            value={allValues.AGE} 
                            name="age"
                            type="text"
                            placeholder="Enter Age"
                            onChange={handleOnchange} />
                        </Form.Group>
                        <Form.Group controlId="formSex">
                            <Form.Label>Sex</Form.Label>
                            <Form.Control 
                            value={allValues.SEX}
                            name="sex" 
                            type="text" 
                            placeholder="Enter Sex"
                            onChange={handleOnchange} />
                        </Form.Group>
                        <Form.Group controlId="formZip">
                            <Form.Label>Zip</Form.Label>
                            <Form.Control 
                            value={allValues.ZIP}
                            name="zip" 
                            type="text" 
                            placeholder="Enter Zip"
                            onChange={handleOnchange} />
                        </Form.Group>
                        <Form.Group controlId="formLatestBMI">
                            <Form.Label>BMI</Form.Label>
                            <Form.Control 
                            value={allValues.LATEST_BMI}
                            name="latestBMI" 
                            type="text" 
                            placeholder="Enter Latest BMI"
                            onChange={handleOnchange} />
                        </Form.Group>
                        <Form.Group controlId="formLatestWeight">
                            <Form.Label>Weight</Form.Label>
                            <Form.Control 
                            value={allValues.LATESTWEIGHT}
                            name="weight" 
                            type="text" 
                            placeholder="Enter Latest Weight"
                            onChange={handleOnchange} />
                        </Form.Group>
                        <Form.Group controlId="formICUAdmit">
                            <Form.Label>ICU Admit</Form.Label>
                            <Form.Control 
                            value={allValues.ICU_Admit}
                            name="ICU Admit" 
                            type="text" 
                            placeholder="Enter Y/N"
                            onChange={handleOnchange} />
                        </Form.Group>
                        <Form.Group controlId="formMortality">
                            <Form.Label>Mortality</Form.Label>
                            <Form.Control 
                            value={allValues.MORTALITY}
                            name="mortality" 
                            type="text" 
                            placeholder="Enter Y/N"
                            onChange={handleOnchange} />
                        </Form.Group>
                        <Form.Group controlId="formImage">
                            <Form.Label>Image</Form.Label>
                            <Form.Control 
                            value={allValues.png_filename}
                            name="pngFilename" 
                            type="text" 
                            placeholder="Enter Image Address"
                            onChange={handleOnchange} />
                        </Form.Group>
                        

                        <Button
                        onClick={handleOnClick} 
                        variant="primary" 
                        type="submit"
                        className="formButton"> 
                        Submit
                        </Button>
                    </Form>
                }
            </div>
        );
}
 
export default XrayForm;